Applying right command policy for CIC
Testing done
Applied the proposed policy to VPX and then used CIC to configure
Note: this user doesn't have shell access. 
This user can do whatever a sysadmin can do. Additionally, it can upload the file to the Citrix ADC which is needed for CIC
Some test output
root@ns# ls abc*           
abc-CBM4MBX6F6R4UOH5HUGXDH56UKI.crt     abc-CBM4MBX6F6R4UOH5HUGXDH56UKI.key
> sh ssl certkey
1)      Name: ns-server-certificate
        Cert Path: /nsconfig/ssl/deepakserver.pem
        Key Path: /nsconfig/ssl/deepakserver_nopass.key
        Format: PEM
        Status: -->Expired<--
        Certificate Expiry Monitor: DISABLED
        Certificate Type:       "Client Certificate"    "Server Certificate"
        Version: 3
        Serial Number: 01
        Signature Algorithm: sha256WithRSAEncryption
        Issuer:  C=US,ST=deepak,L=deepak,O=deepak,OU=deepak,CN=deepak/emailAddress=deepak
        Validity
                Not Before: Apr  5 09:46:59 2018 GMT
                Not After : Apr  5 09:46:59 2019 GMT
        Subject:  C=US,ST=deepakserver,L=deepakserver,O=deepakserver,OU=deepakserver,CN=deepakserver/emailAddress=deepakserver@test.com
        Public Key Algorithm: rsaEncryption
        Public Key size: 2048
        Ocsp Response Status: NONE
2)      Name: abc-CBM4MBX6F6R4UOH5HUGXDH56UKI
        Cert Path: abc-CBM4MBX6F6R4UOH5HUGXDH56UKI.crt
        Key Path: abc-CBM4MBX6F6R4UOH5HUGXDH56UKI.key
        Format: PEM
        Status: -->Expired<--
        Certificate Expiry Monitor: DISABLED
        Certificate Type:       "ROOT CA"       "Client Certificate"    "Server Certificate"
        Version: 3
        Serial Number: C6EBBF8051C04ED0
        Signature Algorithm: sha256WithRSAEncryption
        Issuer:  C=AU,ST=DEEPAK,L=DEEPAK,O=DEEPAK,OU=DEEPAK/emailAddress=deepak.kumar@citrix.com
        Validity
                Not Before: May  9 01:54:36 2018 GMT
                Not After : May  9 01:54:36 2019 GMT
        Subject:  C=AU,ST=DEEPAK,L=DEEPAK,O=DEEPAK,OU=DEEPAK/emailAddress=deepak.kumar@citrix.com
        Public Key Algorithm: rsaEncryption
        Public Key size: 2048
        Ocsp Response Status: NONE
 Done
> shell
ERROR: Not authorized to execute this command [shell]
>